### PR TITLE
change app to path for App

### PR DESCRIPTION
**Pull request by Dylan-DPC**
## Description
Changes `at()` to `path()` for App

## Motivation and Context
#96 

## How Has This Been Tested?
No new tests added. Existing tests modified to reflect the change

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tzilist** [comment]
this looks good to me, just want to cc @aturon to make sure he's alright with it!

**Comment by aturon** [comment]
I don't have a strong preference here, but I'd like to make sure others are on board! cc @bIgBV @tirr-c any thoughts/preferences?

**Comment by bIgBV** [comment]
Both `at` and `path` to me are pretty similar from an implementation stand point. Though that said, I feel that `.at()` communicates the intent of the operation better

> You are mounting an _endpoint_ for the given _method_, _at_ the given _path_

So calling the method `.path()` changes that, and consequently, the documentation surround explaining the concepts becomes more complex.

> You are mounting an _endpoint_ for the given _method_, at the _path_ by calling the `app.path()` method.

But, there might be a better way to communicate this idea, and in that case `.path()` works.

**Comment by DeltaManiac** [comment]
My understanding of `at` was _do something_ _at_ a _path/resource_ , very much like how @bIgBV put it.
Even though `path` might work, I'd still prefer it to be the `at` a path/resource.

**Comment by Dylan-DPC** [comment]
There isn't much to pick between the 2, but imo `path` feels more readable to me.

**Comment by connectkushal** [comment]
as a beginner i think `path` would be more distinct and understandable than `at`. Im more comfortable with a function name that is understandable when looking at the code rather than a function name which makes language of the documentation proper. (code readability over documentation convinience)

**Comment by mmrath** [comment]
I was just playing with tide and `at` feels better to me.

**Comment by yoshuawuyts** [comment]
Something I haven't seen raised before is that `path` already has a meaning within Rust. Namely [`Path`](https://doc.rust-lang.org/std/path/struct.Path.html) and [`PathBuf`](https://doc.rust-lang.org/std/path/struct.PathBuf.html) are used to describe _file system locations_.

It might be a gotcha that Tide's `.path()` method does not take a `Into<Path>` but a string slice. The fact that path now has subtly different behaviors might cause potential issues down the line.

This can be entirely evaded by not using `.path()`, but using a different name instead. For example the existing `.at()` method evades this. Or else something like `.route()` might work (because we add _routes_ to the _router_ using the _`.route()`_ API).

But personally I think `.at()` is good enough actually, and don't think it's worth changing.

**Comment by Dylan-DPC** [comment]
Going by the comments, `at()` looks like a better option so I'm okay with closing this. Thanks

**Pull request closed without merging**
