### PR TITLE
Structopt integration

### PR DESCRIPTION
**Pull request by bIgBV**
## Description

Integrate [`structopt`](https://docs.rs/structopt/) with the default configuration as discussed in #123 . This provides users a way provide application configuration through command line options, environment variables and programmatically override the configuration at app launch

## Motivation and Context

Environment specific configuration is a requirement for web application frameworks as depending on the environment, the application will have different means of communicating with external entities. These may be databases or external APIs. This PR provides a starting point for default application configuration which currently only includes the environment, address and port but could go on to include important items like database connection strings and template directory paths.

## How Has This Been Tested?

Manually tested the output for example applications.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
    - Added new doctests for existing configuration builder
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bIgBV** [comment]
@PeteJodo I purposefully avoided using a database host as a config option as I figured that there would be more discussion around connecting to external data stores and therefore I didn't want to make any assumptions. And yes, I think a rename would be better, but I think that should be a different PR. I'll open it once this lands.

**Comment by bIgBV** [comment]
@yoshuawuyts so when you say an example, are you thinking of something along the lines of struct stored in the app store defined by the user, on which `StructOpt` is derived?

**Comment by yoshuawuyts** [comment]
@bIgBV I was indeed thinking something along the lines of @PeteJodo's example.

**Comment by bIgBV** [comment]
@yoshuawuyts @PeteJodo I'll open a PR adding a similar example and close this one. We can discuss weather or not we want to include this in the framework itself in a separate issue.

**Pull request closed without merging**
