### PR TITLE
Allow running Tide on non-Tokio executors

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by aturon** [comment]
Awesome, thank you!

**Comment by cramertj** [comment]
Oh sorry--  expected this to fail on CI and wait for a bit-- you probably want to revert. This needs a matching change to futures-rs (deriving `Clone` for the `Compat` type), so if you don't have that, you won't be able to build.

**Comment by cramertj** [comment]
(needs https://github.com/rust-lang-nursery/futures-rs/pull/1321, specifically)

**Comment by aturon** [comment]
Done! sorry for the confusion

**Pull request merged**
