### PR TITLE
strip body on head request

### PR DESCRIPTION
**Pull request by tzilist**
Hopefully fixes issue #45. Not sure exactly where this logic belongs but seems to make sense to me. :)

### CODE REVIEW

**Comment by tirr-c** [comment]
The response header of `HEAD` should be identical to those of `GET`, but it is tricky because of `Content-Length` header. It is handled by `Payload` trait from Hyper, which is implemented for `hyper::Body`.

If you give empty body to the response, `Content-Length` will be 0, which leads to the mismatch of headers. We need to implement `Payload` manually, but it requires `Poll` from futures 0.1 (from function signature).

**Comment by tzilist** [comment]
Oh wow, that is a great point! I'll dig into this a bit more then. :)

**Comment by tzilist** [comment]
Holding off on this until questions in #45 are resolved

**Comment by aturon** [comment]
Given how #45 has gone, I'm gonna close this out. It'd be great to get a PR documenting Hyper's behavior and how Tide relies on it, though!

**Pull request closed without merging**
